### ISSUE TITLE
Error in canvas_mesh() : could not find function "canvas_mesh"

### ISSUE THREAD

**Issue by JanBren** [koenderks/aRtsy#160] opened 2022-12-11 10:59 UTC
**Describe the bug**
The following function is not working: canvas_mesh()
Error displayed: Error in canvas_mesh() : could not find function "canvas_mesh"
Thanks

**Comment by koenderks** [comment] 2022-12-11 12:20
Did you use `library(aRtsy)` before calling `canvas_mesh()`? It cannot reproduce this with the latest package from CRAN.

**Comment by koenderks** [comment] 2022-12-20 05:52
Any luck with this? If this has worked, you can close this issue.

**Closed as completed** 2023-01-02 09:16 UTC
Labels: bug
